// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: api_internal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BcApiGatewayInternal_CreateMerchant_FullMethodName               = "/api.BcApiGatewayInternal/CreateMerchant"
	BcApiGatewayInternal_CreateWallet_FullMethodName                 = "/api.BcApiGatewayInternal/CreateWallet"
	BcApiGatewayInternal_CreateAccount_FullMethodName                = "/api.BcApiGatewayInternal/CreateAccount"
	BcApiGatewayInternal_CreateCurrency_FullMethodName               = "/api.BcApiGatewayInternal/CreateCurrency"
	BcApiGatewayInternal_AddAccountCurrency_FullMethodName           = "/api.BcApiGatewayInternal/AddAccountCurrency"
	BcApiGatewayInternal_GetWallets_FullMethodName                   = "/api.BcApiGatewayInternal/GetWallets"
	BcApiGatewayInternal_GetCurrencies_FullMethodName                = "/api.BcApiGatewayInternal/GetCurrencies"
	BcApiGatewayInternal_GetAllWallets_FullMethodName                = "/api.BcApiGatewayInternal/GetAllWallets"
	BcApiGatewayInternal_GetTransaction_FullMethodName               = "/api.BcApiGatewayInternal/GetTransaction"
	BcApiGatewayInternal_GetWithdrawOrder_FullMethodName             = "/api.BcApiGatewayInternal/GetWithdrawOrder"
	BcApiGatewayInternal_GetOrderInfo_FullMethodName                 = "/api.BcApiGatewayInternal/GetOrderInfo"
	BcApiGatewayInternal_GetOrderListByLimitAndOffset_FullMethodName = "/api.BcApiGatewayInternal/GetOrderListByLimitAndOffset"
	BcApiGatewayInternal_GetOrderListByTimeRange_FullMethodName      = "/api.BcApiGatewayInternal/GetOrderListByTimeRange"
	BcApiGatewayInternal_GetEventList_FullMethodName                 = "/api.BcApiGatewayInternal/GetEventList"
)

// BcApiGatewayInternalClient is the client API for BcApiGatewayInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Internal RPC api gateway
type BcApiGatewayInternalClient interface {
	CreateMerchant(ctx context.Context, in *CreateMerchantRequest, opts ...grpc.CallOption) (*CreateMerchantResponse, error)
	CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletResponse, error)
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	CreateCurrency(ctx context.Context, in *CreateCurrencyRequest, opts ...grpc.CallOption) (*CreateCurrencyResponse, error)
	AddAccountCurrency(ctx context.Context, in *AddAccountCurrencyRequest, opts ...grpc.CallOption) (*AddAccountCurrencyResponse, error)
	GetWallets(ctx context.Context, in *GetWalletsRequest, opts ...grpc.CallOption) (*GetWalletsResponse, error)
	GetCurrencies(ctx context.Context, in *GetCurrenciesRequest, opts ...grpc.CallOption) (*GetCurrenciesResponse, error)
	GetAllWallets(ctx context.Context, in *GetAllWalletsRequest, opts ...grpc.CallOption) (*GetAllWalletsResponse, error)
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	GetWithdrawOrder(ctx context.Context, in *GetWithdrawOrderRequest, opts ...grpc.CallOption) (*GetWithdrawOrderResponse, error)
	GetOrderInfo(ctx context.Context, in *GetOrderInfoRequest, opts ...grpc.CallOption) (*GetOrderInfoResponse, error)
	GetOrderListByLimitAndOffset(ctx context.Context, in *GetOrderListByLimitAndOffsetRequest, opts ...grpc.CallOption) (*GetOrderListByLimitAndOffsetResponse, error)
	GetOrderListByTimeRange(ctx context.Context, in *GetOrderListByTimeRangeRequest, opts ...grpc.CallOption) (*GetOrderListByTimeRangeResponse, error)
	GetEventList(ctx context.Context, in *GetEventListRequest, opts ...grpc.CallOption) (*GetEventListResponse, error)
}

type bcApiGatewayInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewBcApiGatewayInternalClient(cc grpc.ClientConnInterface) BcApiGatewayInternalClient {
	return &bcApiGatewayInternalClient{cc}
}

func (c *bcApiGatewayInternalClient) CreateMerchant(ctx context.Context, in *CreateMerchantRequest, opts ...grpc.CallOption) (*CreateMerchantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMerchantResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayInternal_CreateMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayInternalClient) CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWalletResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayInternal_CreateWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayInternalClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayInternal_CreateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayInternalClient) CreateCurrency(ctx context.Context, in *CreateCurrencyRequest, opts ...grpc.CallOption) (*CreateCurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCurrencyResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayInternal_CreateCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayInternalClient) AddAccountCurrency(ctx context.Context, in *AddAccountCurrencyRequest, opts ...grpc.CallOption) (*AddAccountCurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAccountCurrencyResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayInternal_AddAccountCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayInternalClient) GetWallets(ctx context.Context, in *GetWalletsRequest, opts ...grpc.CallOption) (*GetWalletsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletsResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayInternal_GetWallets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayInternalClient) GetCurrencies(ctx context.Context, in *GetCurrenciesRequest, opts ...grpc.CallOption) (*GetCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrenciesResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayInternal_GetCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayInternalClient) GetAllWallets(ctx context.Context, in *GetAllWalletsRequest, opts ...grpc.CallOption) (*GetAllWalletsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllWalletsResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayInternal_GetAllWallets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayInternalClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayInternal_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayInternalClient) GetWithdrawOrder(ctx context.Context, in *GetWithdrawOrderRequest, opts ...grpc.CallOption) (*GetWithdrawOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawOrderResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayInternal_GetWithdrawOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayInternalClient) GetOrderInfo(ctx context.Context, in *GetOrderInfoRequest, opts ...grpc.CallOption) (*GetOrderInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderInfoResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayInternal_GetOrderInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayInternalClient) GetOrderListByLimitAndOffset(ctx context.Context, in *GetOrderListByLimitAndOffsetRequest, opts ...grpc.CallOption) (*GetOrderListByLimitAndOffsetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderListByLimitAndOffsetResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayInternal_GetOrderListByLimitAndOffset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayInternalClient) GetOrderListByTimeRange(ctx context.Context, in *GetOrderListByTimeRangeRequest, opts ...grpc.CallOption) (*GetOrderListByTimeRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderListByTimeRangeResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayInternal_GetOrderListByTimeRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayInternalClient) GetEventList(ctx context.Context, in *GetEventListRequest, opts ...grpc.CallOption) (*GetEventListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventListResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayInternal_GetEventList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BcApiGatewayInternalServer is the server API for BcApiGatewayInternal service.
// All implementations must embed UnimplementedBcApiGatewayInternalServer
// for forward compatibility.
//
// Internal RPC api gateway
type BcApiGatewayInternalServer interface {
	CreateMerchant(context.Context, *CreateMerchantRequest) (*CreateMerchantResponse, error)
	CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error)
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	CreateCurrency(context.Context, *CreateCurrencyRequest) (*CreateCurrencyResponse, error)
	AddAccountCurrency(context.Context, *AddAccountCurrencyRequest) (*AddAccountCurrencyResponse, error)
	GetWallets(context.Context, *GetWalletsRequest) (*GetWalletsResponse, error)
	GetCurrencies(context.Context, *GetCurrenciesRequest) (*GetCurrenciesResponse, error)
	GetAllWallets(context.Context, *GetAllWalletsRequest) (*GetAllWalletsResponse, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	GetWithdrawOrder(context.Context, *GetWithdrawOrderRequest) (*GetWithdrawOrderResponse, error)
	GetOrderInfo(context.Context, *GetOrderInfoRequest) (*GetOrderInfoResponse, error)
	GetOrderListByLimitAndOffset(context.Context, *GetOrderListByLimitAndOffsetRequest) (*GetOrderListByLimitAndOffsetResponse, error)
	GetOrderListByTimeRange(context.Context, *GetOrderListByTimeRangeRequest) (*GetOrderListByTimeRangeResponse, error)
	GetEventList(context.Context, *GetEventListRequest) (*GetEventListResponse, error)
	mustEmbedUnimplementedBcApiGatewayInternalServer()
}

// UnimplementedBcApiGatewayInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBcApiGatewayInternalServer struct{}

func (UnimplementedBcApiGatewayInternalServer) CreateMerchant(context.Context, *CreateMerchantRequest) (*CreateMerchantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMerchant not implemented")
}
func (UnimplementedBcApiGatewayInternalServer) CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWallet not implemented")
}
func (UnimplementedBcApiGatewayInternalServer) CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedBcApiGatewayInternalServer) CreateCurrency(context.Context, *CreateCurrencyRequest) (*CreateCurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCurrency not implemented")
}
func (UnimplementedBcApiGatewayInternalServer) AddAccountCurrency(context.Context, *AddAccountCurrencyRequest) (*AddAccountCurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAccountCurrency not implemented")
}
func (UnimplementedBcApiGatewayInternalServer) GetWallets(context.Context, *GetWalletsRequest) (*GetWalletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWallets not implemented")
}
func (UnimplementedBcApiGatewayInternalServer) GetCurrencies(context.Context, *GetCurrenciesRequest) (*GetCurrenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrencies not implemented")
}
func (UnimplementedBcApiGatewayInternalServer) GetAllWallets(context.Context, *GetAllWalletsRequest) (*GetAllWalletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllWallets not implemented")
}
func (UnimplementedBcApiGatewayInternalServer) GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedBcApiGatewayInternalServer) GetWithdrawOrder(context.Context, *GetWithdrawOrderRequest) (*GetWithdrawOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWithdrawOrder not implemented")
}
func (UnimplementedBcApiGatewayInternalServer) GetOrderInfo(context.Context, *GetOrderInfoRequest) (*GetOrderInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderInfo not implemented")
}
func (UnimplementedBcApiGatewayInternalServer) GetOrderListByLimitAndOffset(context.Context, *GetOrderListByLimitAndOffsetRequest) (*GetOrderListByLimitAndOffsetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderListByLimitAndOffset not implemented")
}
func (UnimplementedBcApiGatewayInternalServer) GetOrderListByTimeRange(context.Context, *GetOrderListByTimeRangeRequest) (*GetOrderListByTimeRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderListByTimeRange not implemented")
}
func (UnimplementedBcApiGatewayInternalServer) GetEventList(context.Context, *GetEventListRequest) (*GetEventListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventList not implemented")
}
func (UnimplementedBcApiGatewayInternalServer) mustEmbedUnimplementedBcApiGatewayInternalServer() {}
func (UnimplementedBcApiGatewayInternalServer) testEmbeddedByValue()                              {}

// UnsafeBcApiGatewayInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BcApiGatewayInternalServer will
// result in compilation errors.
type UnsafeBcApiGatewayInternalServer interface {
	mustEmbedUnimplementedBcApiGatewayInternalServer()
}

func RegisterBcApiGatewayInternalServer(s grpc.ServiceRegistrar, srv BcApiGatewayInternalServer) {
	// If the following call pancis, it indicates UnimplementedBcApiGatewayInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BcApiGatewayInternal_ServiceDesc, srv)
}

func _BcApiGatewayInternal_CreateMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayInternalServer).CreateMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayInternal_CreateMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayInternalServer).CreateMerchant(ctx, req.(*CreateMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayInternal_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayInternalServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayInternal_CreateWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayInternalServer).CreateWallet(ctx, req.(*CreateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayInternal_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayInternalServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayInternal_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayInternalServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayInternal_CreateCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayInternalServer).CreateCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayInternal_CreateCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayInternalServer).CreateCurrency(ctx, req.(*CreateCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayInternal_AddAccountCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccountCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayInternalServer).AddAccountCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayInternal_AddAccountCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayInternalServer).AddAccountCurrency(ctx, req.(*AddAccountCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayInternal_GetWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayInternalServer).GetWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayInternal_GetWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayInternalServer).GetWallets(ctx, req.(*GetWalletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayInternal_GetCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayInternalServer).GetCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayInternal_GetCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayInternalServer).GetCurrencies(ctx, req.(*GetCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayInternal_GetAllWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllWalletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayInternalServer).GetAllWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayInternal_GetAllWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayInternalServer).GetAllWallets(ctx, req.(*GetAllWalletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayInternal_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayInternalServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayInternal_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayInternalServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayInternal_GetWithdrawOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayInternalServer).GetWithdrawOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayInternal_GetWithdrawOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayInternalServer).GetWithdrawOrder(ctx, req.(*GetWithdrawOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayInternal_GetOrderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayInternalServer).GetOrderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayInternal_GetOrderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayInternalServer).GetOrderInfo(ctx, req.(*GetOrderInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayInternal_GetOrderListByLimitAndOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderListByLimitAndOffsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayInternalServer).GetOrderListByLimitAndOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayInternal_GetOrderListByLimitAndOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayInternalServer).GetOrderListByLimitAndOffset(ctx, req.(*GetOrderListByLimitAndOffsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayInternal_GetOrderListByTimeRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderListByTimeRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayInternalServer).GetOrderListByTimeRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayInternal_GetOrderListByTimeRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayInternalServer).GetOrderListByTimeRange(ctx, req.(*GetOrderListByTimeRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayInternal_GetEventList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayInternalServer).GetEventList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayInternal_GetEventList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayInternalServer).GetEventList(ctx, req.(*GetEventListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BcApiGatewayInternal_ServiceDesc is the grpc.ServiceDesc for BcApiGatewayInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BcApiGatewayInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.BcApiGatewayInternal",
	HandlerType: (*BcApiGatewayInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMerchant",
			Handler:    _BcApiGatewayInternal_CreateMerchant_Handler,
		},
		{
			MethodName: "CreateWallet",
			Handler:    _BcApiGatewayInternal_CreateWallet_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _BcApiGatewayInternal_CreateAccount_Handler,
		},
		{
			MethodName: "CreateCurrency",
			Handler:    _BcApiGatewayInternal_CreateCurrency_Handler,
		},
		{
			MethodName: "AddAccountCurrency",
			Handler:    _BcApiGatewayInternal_AddAccountCurrency_Handler,
		},
		{
			MethodName: "GetWallets",
			Handler:    _BcApiGatewayInternal_GetWallets_Handler,
		},
		{
			MethodName: "GetCurrencies",
			Handler:    _BcApiGatewayInternal_GetCurrencies_Handler,
		},
		{
			MethodName: "GetAllWallets",
			Handler:    _BcApiGatewayInternal_GetAllWallets_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _BcApiGatewayInternal_GetTransaction_Handler,
		},
		{
			MethodName: "GetWithdrawOrder",
			Handler:    _BcApiGatewayInternal_GetWithdrawOrder_Handler,
		},
		{
			MethodName: "GetOrderInfo",
			Handler:    _BcApiGatewayInternal_GetOrderInfo_Handler,
		},
		{
			MethodName: "GetOrderListByLimitAndOffset",
			Handler:    _BcApiGatewayInternal_GetOrderListByLimitAndOffset_Handler,
		},
		{
			MethodName: "GetOrderListByTimeRange",
			Handler:    _BcApiGatewayInternal_GetOrderListByTimeRange_Handler,
		},
		{
			MethodName: "GetEventList",
			Handler:    _BcApiGatewayInternal_GetEventList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_internal.proto",
}
