// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api_merchant.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_merchant_proto protoreflect.FileDescriptor

const file_api_merchant_proto_rawDesc = "" +
	"\n" +
	"\x12api_merchant.proto\x12\x03api\x1a\x0emessages.proto\x1a\x1cgoogle/api/annotations.proto2\x8f\f\n" +
	"\x14BcApiGatewayMerchant\x12Z\n" +
	"\x13CreateWithdrawOrder\x12\x1f.api.CreateWithdrawOrderRequest\x1a .api.CreateWithdrawOrderResponse\"\x00\x12W\n" +
	"\x12AddAccountCurrency\x12\x1e.api.AddAccountCurrencyRequest\x1a\x1f.api.AddAccountCurrencyResponse\"\x00\x12T\n" +
	"\x11GetDepositAddress\x12\x1d.api.GetDepositAddressRequest\x1a\x1e.api.GetDepositAddressResponse\"\x00\x12Q\n" +
	"\x10GetEstimationFee\x12\x1c.api.GetEstimationFeeRequest\x1a\x1d.api.GetEstimationFeeResponse\"\x00\x12K\n" +
	"\x0eGetTransaction\x12\x1a.api.GetTransactionRequest\x1a\x1b.api.GetTransactionResponse\"\x00\x12Q\n" +
	"\x10GetWithdrawOrder\x12\x1c.api.GetWithdrawOrderRequest\x1a\x1d.api.GetWithdrawOrderResponse\"\x00\x12u\n" +
	"\x1cGetOrderListByLimitAndOffset\x12(.api.GetOrderListByLimitAndOffsetRequest\x1a).api.GetOrderListByLimitAndOffsetResponse\"\x00\x12\x85\x01\n" +
	"\n" +
	"GetWallets\x12\x16.api.GetWalletsRequest\x1a\x17.api.GetWalletsResponse\"F\x82\xd3\xe4\x93\x02@\x12>/api/admin/GetWallets/{NetworkIdentifier}/{ProviderIdentifier}\x12h\n" +
	"\rGetCurrencies\x12\x19.api.GetCurrenciesRequest\x1a\x1a.api.GetCurrenciesResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/admin/GetCurrencies\x12\x9c\x01\n" +
	"\x10GetWalletBalance\x12\x1c.api.GetWalletBalanceRequest\x1a\x1d.api.GetWalletBalanceResponse\"K\x82\xd3\xe4\x93\x02E\x12C/api/admin/GetBalance/{NetworkIdentifier}/{CurrencyIdentifier.UUID}\x12\xa0\x01\n" +
	"\fGetOrderInfo\x12\x18.api.GetOrderInfoRequest\x1a\x19.api.GetOrderInfoResponse\"[\x82\xd3\xe4\x93\x02U\x12S/api/admin/GetOrder/{NetworkIdentifier}/{ProviderIdentifier}/{OrderIdentifier.UUID}\x12\xa4\x01\n" +
	"\x17GetOrderListByTimeRange\x12#.api.GetOrderListByTimeRangeRequest\x1a$.api.GetOrderListByTimeRangeResponse\">\x82\xd3\xe4\x93\x028\x126/api/admin/GetOrders/{TimeRange.Start}/{TimeRange.End}\x12\xa6\x01\n" +
	"\fGetEventList\x12\x18.api.GetEventListRequest\x1a\x19.api.GetEventListResponse\"a\x82\xd3\xe4\x93\x02[\x12Y/api/admin/GetOrderEvents/{NetworkIdentifier}/{ProviderIdentifier}/{OrderIdentifier.UUID}BBZ@github.com/crypto-bundle/bc-api-gateway-proto/pkg/grpc/api/protob\x06proto3"

var file_api_merchant_proto_goTypes = []any{
	(*CreateWithdrawOrderRequest)(nil),           // 0: api.CreateWithdrawOrderRequest
	(*AddAccountCurrencyRequest)(nil),            // 1: api.AddAccountCurrencyRequest
	(*GetDepositAddressRequest)(nil),             // 2: api.GetDepositAddressRequest
	(*GetEstimationFeeRequest)(nil),              // 3: api.GetEstimationFeeRequest
	(*GetTransactionRequest)(nil),                // 4: api.GetTransactionRequest
	(*GetWithdrawOrderRequest)(nil),              // 5: api.GetWithdrawOrderRequest
	(*GetOrderListByLimitAndOffsetRequest)(nil),  // 6: api.GetOrderListByLimitAndOffsetRequest
	(*GetWalletsRequest)(nil),                    // 7: api.GetWalletsRequest
	(*GetCurrenciesRequest)(nil),                 // 8: api.GetCurrenciesRequest
	(*GetWalletBalanceRequest)(nil),              // 9: api.GetWalletBalanceRequest
	(*GetOrderInfoRequest)(nil),                  // 10: api.GetOrderInfoRequest
	(*GetOrderListByTimeRangeRequest)(nil),       // 11: api.GetOrderListByTimeRangeRequest
	(*GetEventListRequest)(nil),                  // 12: api.GetEventListRequest
	(*CreateWithdrawOrderResponse)(nil),          // 13: api.CreateWithdrawOrderResponse
	(*AddAccountCurrencyResponse)(nil),           // 14: api.AddAccountCurrencyResponse
	(*GetDepositAddressResponse)(nil),            // 15: api.GetDepositAddressResponse
	(*GetEstimationFeeResponse)(nil),             // 16: api.GetEstimationFeeResponse
	(*GetTransactionResponse)(nil),               // 17: api.GetTransactionResponse
	(*GetWithdrawOrderResponse)(nil),             // 18: api.GetWithdrawOrderResponse
	(*GetOrderListByLimitAndOffsetResponse)(nil), // 19: api.GetOrderListByLimitAndOffsetResponse
	(*GetWalletsResponse)(nil),                   // 20: api.GetWalletsResponse
	(*GetCurrenciesResponse)(nil),                // 21: api.GetCurrenciesResponse
	(*GetWalletBalanceResponse)(nil),             // 22: api.GetWalletBalanceResponse
	(*GetOrderInfoResponse)(nil),                 // 23: api.GetOrderInfoResponse
	(*GetOrderListByTimeRangeResponse)(nil),      // 24: api.GetOrderListByTimeRangeResponse
	(*GetEventListResponse)(nil),                 // 25: api.GetEventListResponse
}
var file_api_merchant_proto_depIdxs = []int32{
	0,  // 0: api.BcApiGatewayMerchant.CreateWithdrawOrder:input_type -> api.CreateWithdrawOrderRequest
	1,  // 1: api.BcApiGatewayMerchant.AddAccountCurrency:input_type -> api.AddAccountCurrencyRequest
	2,  // 2: api.BcApiGatewayMerchant.GetDepositAddress:input_type -> api.GetDepositAddressRequest
	3,  // 3: api.BcApiGatewayMerchant.GetEstimationFee:input_type -> api.GetEstimationFeeRequest
	4,  // 4: api.BcApiGatewayMerchant.GetTransaction:input_type -> api.GetTransactionRequest
	5,  // 5: api.BcApiGatewayMerchant.GetWithdrawOrder:input_type -> api.GetWithdrawOrderRequest
	6,  // 6: api.BcApiGatewayMerchant.GetOrderListByLimitAndOffset:input_type -> api.GetOrderListByLimitAndOffsetRequest
	7,  // 7: api.BcApiGatewayMerchant.GetWallets:input_type -> api.GetWalletsRequest
	8,  // 8: api.BcApiGatewayMerchant.GetCurrencies:input_type -> api.GetCurrenciesRequest
	9,  // 9: api.BcApiGatewayMerchant.GetWalletBalance:input_type -> api.GetWalletBalanceRequest
	10, // 10: api.BcApiGatewayMerchant.GetOrderInfo:input_type -> api.GetOrderInfoRequest
	11, // 11: api.BcApiGatewayMerchant.GetOrderListByTimeRange:input_type -> api.GetOrderListByTimeRangeRequest
	12, // 12: api.BcApiGatewayMerchant.GetEventList:input_type -> api.GetEventListRequest
	13, // 13: api.BcApiGatewayMerchant.CreateWithdrawOrder:output_type -> api.CreateWithdrawOrderResponse
	14, // 14: api.BcApiGatewayMerchant.AddAccountCurrency:output_type -> api.AddAccountCurrencyResponse
	15, // 15: api.BcApiGatewayMerchant.GetDepositAddress:output_type -> api.GetDepositAddressResponse
	16, // 16: api.BcApiGatewayMerchant.GetEstimationFee:output_type -> api.GetEstimationFeeResponse
	17, // 17: api.BcApiGatewayMerchant.GetTransaction:output_type -> api.GetTransactionResponse
	18, // 18: api.BcApiGatewayMerchant.GetWithdrawOrder:output_type -> api.GetWithdrawOrderResponse
	19, // 19: api.BcApiGatewayMerchant.GetOrderListByLimitAndOffset:output_type -> api.GetOrderListByLimitAndOffsetResponse
	20, // 20: api.BcApiGatewayMerchant.GetWallets:output_type -> api.GetWalletsResponse
	21, // 21: api.BcApiGatewayMerchant.GetCurrencies:output_type -> api.GetCurrenciesResponse
	22, // 22: api.BcApiGatewayMerchant.GetWalletBalance:output_type -> api.GetWalletBalanceResponse
	23, // 23: api.BcApiGatewayMerchant.GetOrderInfo:output_type -> api.GetOrderInfoResponse
	24, // 24: api.BcApiGatewayMerchant.GetOrderListByTimeRange:output_type -> api.GetOrderListByTimeRangeResponse
	25, // 25: api.BcApiGatewayMerchant.GetEventList:output_type -> api.GetEventListResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_merchant_proto_init() }
func file_api_merchant_proto_init() {
	if File_api_merchant_proto != nil {
		return
	}
	file_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_merchant_proto_rawDesc), len(file_api_merchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_merchant_proto_goTypes,
		DependencyIndexes: file_api_merchant_proto_depIdxs,
	}.Build()
	File_api_merchant_proto = out.File
	file_api_merchant_proto_goTypes = nil
	file_api_merchant_proto_depIdxs = nil
}
