// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: api_merchant.proto

/*
Package proto is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package proto

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_BcApiGatewayMerchant_CreateWithdrawOrder_0(ctx context.Context, marshaler runtime.Marshaler, client BcApiGatewayMerchantClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq CreateWithdrawOrderRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.CreateWithdrawOrder(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_BcApiGatewayMerchant_CreateWithdrawOrder_0(ctx context.Context, marshaler runtime.Marshaler, server BcApiGatewayMerchantServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq CreateWithdrawOrderRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.CreateWithdrawOrder(ctx, &protoReq)
	return msg, metadata, err
}

func request_BcApiGatewayMerchant_AddAccountCurrency_0(ctx context.Context, marshaler runtime.Marshaler, client BcApiGatewayMerchantClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq AddAccountCurrencyRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.AddAccountCurrency(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_BcApiGatewayMerchant_AddAccountCurrency_0(ctx context.Context, marshaler runtime.Marshaler, server BcApiGatewayMerchantServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq AddAccountCurrencyRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.AddAccountCurrency(ctx, &protoReq)
	return msg, metadata, err
}

func request_BcApiGatewayMerchant_GetDepositAddress_0(ctx context.Context, marshaler runtime.Marshaler, client BcApiGatewayMerchantClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetDepositAddressRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.GetDepositAddress(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_BcApiGatewayMerchant_GetDepositAddress_0(ctx context.Context, marshaler runtime.Marshaler, server BcApiGatewayMerchantServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetDepositAddressRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.GetDepositAddress(ctx, &protoReq)
	return msg, metadata, err
}

func request_BcApiGatewayMerchant_GetEstimationFee_0(ctx context.Context, marshaler runtime.Marshaler, client BcApiGatewayMerchantClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetEstimationFeeRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.GetEstimationFee(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_BcApiGatewayMerchant_GetEstimationFee_0(ctx context.Context, marshaler runtime.Marshaler, server BcApiGatewayMerchantServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetEstimationFeeRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.GetEstimationFee(ctx, &protoReq)
	return msg, metadata, err
}

func request_BcApiGatewayMerchant_GetTransaction_0(ctx context.Context, marshaler runtime.Marshaler, client BcApiGatewayMerchantClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetTransactionRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.GetTransaction(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_BcApiGatewayMerchant_GetTransaction_0(ctx context.Context, marshaler runtime.Marshaler, server BcApiGatewayMerchantServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetTransactionRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.GetTransaction(ctx, &protoReq)
	return msg, metadata, err
}

func request_BcApiGatewayMerchant_GetWithdrawOrder_0(ctx context.Context, marshaler runtime.Marshaler, client BcApiGatewayMerchantClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetWithdrawOrderRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.GetWithdrawOrder(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_BcApiGatewayMerchant_GetWithdrawOrder_0(ctx context.Context, marshaler runtime.Marshaler, server BcApiGatewayMerchantServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetWithdrawOrderRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.GetWithdrawOrder(ctx, &protoReq)
	return msg, metadata, err
}

func request_BcApiGatewayMerchant_GetOrderListByLimitAndOffset_0(ctx context.Context, marshaler runtime.Marshaler, client BcApiGatewayMerchantClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetOrderListByLimitAndOffsetRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.GetOrderListByLimitAndOffset(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_BcApiGatewayMerchant_GetOrderListByLimitAndOffset_0(ctx context.Context, marshaler runtime.Marshaler, server BcApiGatewayMerchantServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetOrderListByLimitAndOffsetRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.GetOrderListByLimitAndOffset(ctx, &protoReq)
	return msg, metadata, err
}

var filter_BcApiGatewayMerchant_GetWallets_0 = &utilities.DoubleArray{Encoding: map[string]int{"NetworkIdentifier": 0, "ProviderIdentifier": 1}, Base: []int{1, 1, 2, 0, 0}, Check: []int{0, 1, 1, 2, 3}}

func request_BcApiGatewayMerchant_GetWallets_0(ctx context.Context, marshaler runtime.Marshaler, client BcApiGatewayMerchantClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetWalletsRequest
		metadata runtime.ServerMetadata
		e        int32
		err      error
	)
	io.Copy(io.Discard, req.Body)
	val, ok := pathParams["NetworkIdentifier"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "NetworkIdentifier")
	}
	e, err = runtime.Enum(val, Network_value)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "NetworkIdentifier", err)
	}
	protoReq.NetworkIdentifier = Network(e)
	val, ok = pathParams["ProviderIdentifier"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "ProviderIdentifier")
	}
	e, err = runtime.Enum(val, Provider_value)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "ProviderIdentifier", err)
	}
	protoReq.ProviderIdentifier = Provider(e)
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_BcApiGatewayMerchant_GetWallets_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.GetWallets(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_BcApiGatewayMerchant_GetWallets_0(ctx context.Context, marshaler runtime.Marshaler, server BcApiGatewayMerchantServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetWalletsRequest
		metadata runtime.ServerMetadata
		e        int32
		err      error
	)
	val, ok := pathParams["NetworkIdentifier"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "NetworkIdentifier")
	}
	e, err = runtime.Enum(val, Network_value)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "NetworkIdentifier", err)
	}
	protoReq.NetworkIdentifier = Network(e)
	val, ok = pathParams["ProviderIdentifier"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "ProviderIdentifier")
	}
	e, err = runtime.Enum(val, Provider_value)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "ProviderIdentifier", err)
	}
	protoReq.ProviderIdentifier = Provider(e)
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_BcApiGatewayMerchant_GetWallets_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.GetWallets(ctx, &protoReq)
	return msg, metadata, err
}

func request_BcApiGatewayMerchant_GetCurrencies_0(ctx context.Context, marshaler runtime.Marshaler, client BcApiGatewayMerchantClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetCurrenciesRequest
		metadata runtime.ServerMetadata
	)
	io.Copy(io.Discard, req.Body)
	msg, err := client.GetCurrencies(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_BcApiGatewayMerchant_GetCurrencies_0(ctx context.Context, marshaler runtime.Marshaler, server BcApiGatewayMerchantServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetCurrenciesRequest
		metadata runtime.ServerMetadata
	)
	msg, err := server.GetCurrencies(ctx, &protoReq)
	return msg, metadata, err
}

var filter_BcApiGatewayMerchant_GetWalletBalance_0 = &utilities.DoubleArray{Encoding: map[string]int{"NetworkIdentifier": 0, "CurrencyIdentifier": 1, "UUID": 2}, Base: []int{1, 1, 1, 2, 0, 0}, Check: []int{0, 1, 1, 3, 2, 4}}

func request_BcApiGatewayMerchant_GetWalletBalance_0(ctx context.Context, marshaler runtime.Marshaler, client BcApiGatewayMerchantClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetWalletBalanceRequest
		metadata runtime.ServerMetadata
		e        int32
		err      error
	)
	io.Copy(io.Discard, req.Body)
	val, ok := pathParams["NetworkIdentifier"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "NetworkIdentifier")
	}
	e, err = runtime.Enum(val, Network_value)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "NetworkIdentifier", err)
	}
	protoReq.NetworkIdentifier = Network(e)
	val, ok = pathParams["CurrencyIdentifier.UUID"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "CurrencyIdentifier.UUID")
	}
	err = runtime.PopulateFieldFromPath(&protoReq, "CurrencyIdentifier.UUID", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "CurrencyIdentifier.UUID", err)
	}
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_BcApiGatewayMerchant_GetWalletBalance_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.GetWalletBalance(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_BcApiGatewayMerchant_GetWalletBalance_0(ctx context.Context, marshaler runtime.Marshaler, server BcApiGatewayMerchantServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetWalletBalanceRequest
		metadata runtime.ServerMetadata
		e        int32
		err      error
	)
	val, ok := pathParams["NetworkIdentifier"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "NetworkIdentifier")
	}
	e, err = runtime.Enum(val, Network_value)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "NetworkIdentifier", err)
	}
	protoReq.NetworkIdentifier = Network(e)
	val, ok = pathParams["CurrencyIdentifier.UUID"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "CurrencyIdentifier.UUID")
	}
	err = runtime.PopulateFieldFromPath(&protoReq, "CurrencyIdentifier.UUID", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "CurrencyIdentifier.UUID", err)
	}
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_BcApiGatewayMerchant_GetWalletBalance_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.GetWalletBalance(ctx, &protoReq)
	return msg, metadata, err
}

var filter_BcApiGatewayMerchant_GetOrderInfo_0 = &utilities.DoubleArray{Encoding: map[string]int{"NetworkIdentifier": 0, "ProviderIdentifier": 1, "OrderIdentifier": 2, "UUID": 3}, Base: []int{1, 1, 2, 1, 3, 0, 0, 0}, Check: []int{0, 1, 1, 1, 4, 2, 3, 5}}

func request_BcApiGatewayMerchant_GetOrderInfo_0(ctx context.Context, marshaler runtime.Marshaler, client BcApiGatewayMerchantClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetOrderInfoRequest
		metadata runtime.ServerMetadata
		e        int32
		err      error
	)
	io.Copy(io.Discard, req.Body)
	val, ok := pathParams["NetworkIdentifier"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "NetworkIdentifier")
	}
	e, err = runtime.Enum(val, Network_value)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "NetworkIdentifier", err)
	}
	protoReq.NetworkIdentifier = Network(e)
	val, ok = pathParams["ProviderIdentifier"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "ProviderIdentifier")
	}
	e, err = runtime.Enum(val, Provider_value)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "ProviderIdentifier", err)
	}
	protoReq.ProviderIdentifier = Provider(e)
	val, ok = pathParams["OrderIdentifier.UUID"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "OrderIdentifier.UUID")
	}
	err = runtime.PopulateFieldFromPath(&protoReq, "OrderIdentifier.UUID", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "OrderIdentifier.UUID", err)
	}
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_BcApiGatewayMerchant_GetOrderInfo_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.GetOrderInfo(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_BcApiGatewayMerchant_GetOrderInfo_0(ctx context.Context, marshaler runtime.Marshaler, server BcApiGatewayMerchantServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetOrderInfoRequest
		metadata runtime.ServerMetadata
		e        int32
		err      error
	)
	val, ok := pathParams["NetworkIdentifier"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "NetworkIdentifier")
	}
	e, err = runtime.Enum(val, Network_value)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "NetworkIdentifier", err)
	}
	protoReq.NetworkIdentifier = Network(e)
	val, ok = pathParams["ProviderIdentifier"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "ProviderIdentifier")
	}
	e, err = runtime.Enum(val, Provider_value)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "ProviderIdentifier", err)
	}
	protoReq.ProviderIdentifier = Provider(e)
	val, ok = pathParams["OrderIdentifier.UUID"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "OrderIdentifier.UUID")
	}
	err = runtime.PopulateFieldFromPath(&protoReq, "OrderIdentifier.UUID", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "OrderIdentifier.UUID", err)
	}
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_BcApiGatewayMerchant_GetOrderInfo_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.GetOrderInfo(ctx, &protoReq)
	return msg, metadata, err
}

var filter_BcApiGatewayMerchant_GetOrderListByTimeRange_0 = &utilities.DoubleArray{Encoding: map[string]int{"TimeRange": 0, "Start": 1, "End": 2}, Base: []int{1, 1, 1, 2, 0, 0}, Check: []int{0, 1, 2, 2, 3, 4}}

func request_BcApiGatewayMerchant_GetOrderListByTimeRange_0(ctx context.Context, marshaler runtime.Marshaler, client BcApiGatewayMerchantClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetOrderListByTimeRangeRequest
		metadata runtime.ServerMetadata
		err      error
	)
	io.Copy(io.Discard, req.Body)
	val, ok := pathParams["TimeRange.Start"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "TimeRange.Start")
	}
	err = runtime.PopulateFieldFromPath(&protoReq, "TimeRange.Start", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "TimeRange.Start", err)
	}
	val, ok = pathParams["TimeRange.End"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "TimeRange.End")
	}
	err = runtime.PopulateFieldFromPath(&protoReq, "TimeRange.End", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "TimeRange.End", err)
	}
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_BcApiGatewayMerchant_GetOrderListByTimeRange_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.GetOrderListByTimeRange(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_BcApiGatewayMerchant_GetOrderListByTimeRange_0(ctx context.Context, marshaler runtime.Marshaler, server BcApiGatewayMerchantServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetOrderListByTimeRangeRequest
		metadata runtime.ServerMetadata
		err      error
	)
	val, ok := pathParams["TimeRange.Start"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "TimeRange.Start")
	}
	err = runtime.PopulateFieldFromPath(&protoReq, "TimeRange.Start", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "TimeRange.Start", err)
	}
	val, ok = pathParams["TimeRange.End"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "TimeRange.End")
	}
	err = runtime.PopulateFieldFromPath(&protoReq, "TimeRange.End", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "TimeRange.End", err)
	}
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_BcApiGatewayMerchant_GetOrderListByTimeRange_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.GetOrderListByTimeRange(ctx, &protoReq)
	return msg, metadata, err
}

var filter_BcApiGatewayMerchant_GetEventList_0 = &utilities.DoubleArray{Encoding: map[string]int{"NetworkIdentifier": 0, "ProviderIdentifier": 1, "OrderIdentifier": 2, "UUID": 3}, Base: []int{1, 1, 2, 1, 3, 0, 0, 0}, Check: []int{0, 1, 1, 1, 4, 2, 3, 5}}

func request_BcApiGatewayMerchant_GetEventList_0(ctx context.Context, marshaler runtime.Marshaler, client BcApiGatewayMerchantClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetEventListRequest
		metadata runtime.ServerMetadata
		e        int32
		err      error
	)
	io.Copy(io.Discard, req.Body)
	val, ok := pathParams["NetworkIdentifier"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "NetworkIdentifier")
	}
	e, err = runtime.Enum(val, Network_value)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "NetworkIdentifier", err)
	}
	protoReq.NetworkIdentifier = Network(e)
	val, ok = pathParams["ProviderIdentifier"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "ProviderIdentifier")
	}
	e, err = runtime.Enum(val, Provider_value)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "ProviderIdentifier", err)
	}
	protoReq.ProviderIdentifier = Provider(e)
	val, ok = pathParams["OrderIdentifier.UUID"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "OrderIdentifier.UUID")
	}
	err = runtime.PopulateFieldFromPath(&protoReq, "OrderIdentifier.UUID", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "OrderIdentifier.UUID", err)
	}
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_BcApiGatewayMerchant_GetEventList_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.GetEventList(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_BcApiGatewayMerchant_GetEventList_0(ctx context.Context, marshaler runtime.Marshaler, server BcApiGatewayMerchantServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetEventListRequest
		metadata runtime.ServerMetadata
		e        int32
		err      error
	)
	val, ok := pathParams["NetworkIdentifier"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "NetworkIdentifier")
	}
	e, err = runtime.Enum(val, Network_value)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "NetworkIdentifier", err)
	}
	protoReq.NetworkIdentifier = Network(e)
	val, ok = pathParams["ProviderIdentifier"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "ProviderIdentifier")
	}
	e, err = runtime.Enum(val, Provider_value)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "ProviderIdentifier", err)
	}
	protoReq.ProviderIdentifier = Provider(e)
	val, ok = pathParams["OrderIdentifier.UUID"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "OrderIdentifier.UUID")
	}
	err = runtime.PopulateFieldFromPath(&protoReq, "OrderIdentifier.UUID", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "OrderIdentifier.UUID", err)
	}
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_BcApiGatewayMerchant_GetEventList_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.GetEventList(ctx, &protoReq)
	return msg, metadata, err
}

// RegisterBcApiGatewayMerchantHandlerServer registers the http handlers for service BcApiGatewayMerchant to "mux".
// UnaryRPC     :call BcApiGatewayMerchantServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterBcApiGatewayMerchantHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterBcApiGatewayMerchantHandlerServer(ctx context.Context, mux *runtime.ServeMux, server BcApiGatewayMerchantServer) error {
	mux.Handle(http.MethodPost, pattern_BcApiGatewayMerchant_CreateWithdrawOrder_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/api.BcApiGatewayMerchant/CreateWithdrawOrder", runtime.WithHTTPPathPattern("/api.BcApiGatewayMerchant/CreateWithdrawOrder"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_BcApiGatewayMerchant_CreateWithdrawOrder_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_CreateWithdrawOrder_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_BcApiGatewayMerchant_AddAccountCurrency_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/api.BcApiGatewayMerchant/AddAccountCurrency", runtime.WithHTTPPathPattern("/api.BcApiGatewayMerchant/AddAccountCurrency"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_BcApiGatewayMerchant_AddAccountCurrency_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_AddAccountCurrency_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_BcApiGatewayMerchant_GetDepositAddress_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetDepositAddress", runtime.WithHTTPPathPattern("/api.BcApiGatewayMerchant/GetDepositAddress"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_BcApiGatewayMerchant_GetDepositAddress_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetDepositAddress_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_BcApiGatewayMerchant_GetEstimationFee_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetEstimationFee", runtime.WithHTTPPathPattern("/api.BcApiGatewayMerchant/GetEstimationFee"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_BcApiGatewayMerchant_GetEstimationFee_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetEstimationFee_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_BcApiGatewayMerchant_GetTransaction_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetTransaction", runtime.WithHTTPPathPattern("/api.BcApiGatewayMerchant/GetTransaction"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_BcApiGatewayMerchant_GetTransaction_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetTransaction_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_BcApiGatewayMerchant_GetWithdrawOrder_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetWithdrawOrder", runtime.WithHTTPPathPattern("/api.BcApiGatewayMerchant/GetWithdrawOrder"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_BcApiGatewayMerchant_GetWithdrawOrder_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetWithdrawOrder_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_BcApiGatewayMerchant_GetOrderListByLimitAndOffset_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetOrderListByLimitAndOffset", runtime.WithHTTPPathPattern("/api.BcApiGatewayMerchant/GetOrderListByLimitAndOffset"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_BcApiGatewayMerchant_GetOrderListByLimitAndOffset_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetOrderListByLimitAndOffset_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_BcApiGatewayMerchant_GetWallets_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetWallets", runtime.WithHTTPPathPattern("/api/admin/GetWallets/{NetworkIdentifier}/{ProviderIdentifier}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_BcApiGatewayMerchant_GetWallets_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetWallets_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_BcApiGatewayMerchant_GetCurrencies_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetCurrencies", runtime.WithHTTPPathPattern("/api/admin/GetCurrencies"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_BcApiGatewayMerchant_GetCurrencies_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetCurrencies_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_BcApiGatewayMerchant_GetWalletBalance_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetWalletBalance", runtime.WithHTTPPathPattern("/api/admin/GetBalance/{NetworkIdentifier}/{CurrencyIdentifier.UUID}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_BcApiGatewayMerchant_GetWalletBalance_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetWalletBalance_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_BcApiGatewayMerchant_GetOrderInfo_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetOrderInfo", runtime.WithHTTPPathPattern("/api/admin/GetOrder/{NetworkIdentifier}/{ProviderIdentifier}/{OrderIdentifier.UUID}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_BcApiGatewayMerchant_GetOrderInfo_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetOrderInfo_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_BcApiGatewayMerchant_GetOrderListByTimeRange_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetOrderListByTimeRange", runtime.WithHTTPPathPattern("/api/admin/GetOrders/{TimeRange.Start}/{TimeRange.End}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_BcApiGatewayMerchant_GetOrderListByTimeRange_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetOrderListByTimeRange_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_BcApiGatewayMerchant_GetEventList_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetEventList", runtime.WithHTTPPathPattern("/api/admin/GetOrderEvents/{NetworkIdentifier}/{ProviderIdentifier}/{OrderIdentifier.UUID}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_BcApiGatewayMerchant_GetEventList_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetEventList_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})

	return nil
}

// RegisterBcApiGatewayMerchantHandlerFromEndpoint is same as RegisterBcApiGatewayMerchantHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterBcApiGatewayMerchantHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()
	return RegisterBcApiGatewayMerchantHandler(ctx, mux, conn)
}

// RegisterBcApiGatewayMerchantHandler registers the http handlers for service BcApiGatewayMerchant to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterBcApiGatewayMerchantHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterBcApiGatewayMerchantHandlerClient(ctx, mux, NewBcApiGatewayMerchantClient(conn))
}

// RegisterBcApiGatewayMerchantHandlerClient registers the http handlers for service BcApiGatewayMerchant
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "BcApiGatewayMerchantClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "BcApiGatewayMerchantClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "BcApiGatewayMerchantClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterBcApiGatewayMerchantHandlerClient(ctx context.Context, mux *runtime.ServeMux, client BcApiGatewayMerchantClient) error {
	mux.Handle(http.MethodPost, pattern_BcApiGatewayMerchant_CreateWithdrawOrder_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/api.BcApiGatewayMerchant/CreateWithdrawOrder", runtime.WithHTTPPathPattern("/api.BcApiGatewayMerchant/CreateWithdrawOrder"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BcApiGatewayMerchant_CreateWithdrawOrder_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_CreateWithdrawOrder_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_BcApiGatewayMerchant_AddAccountCurrency_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/api.BcApiGatewayMerchant/AddAccountCurrency", runtime.WithHTTPPathPattern("/api.BcApiGatewayMerchant/AddAccountCurrency"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BcApiGatewayMerchant_AddAccountCurrency_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_AddAccountCurrency_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_BcApiGatewayMerchant_GetDepositAddress_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetDepositAddress", runtime.WithHTTPPathPattern("/api.BcApiGatewayMerchant/GetDepositAddress"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BcApiGatewayMerchant_GetDepositAddress_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetDepositAddress_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_BcApiGatewayMerchant_GetEstimationFee_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetEstimationFee", runtime.WithHTTPPathPattern("/api.BcApiGatewayMerchant/GetEstimationFee"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BcApiGatewayMerchant_GetEstimationFee_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetEstimationFee_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_BcApiGatewayMerchant_GetTransaction_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetTransaction", runtime.WithHTTPPathPattern("/api.BcApiGatewayMerchant/GetTransaction"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BcApiGatewayMerchant_GetTransaction_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetTransaction_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_BcApiGatewayMerchant_GetWithdrawOrder_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetWithdrawOrder", runtime.WithHTTPPathPattern("/api.BcApiGatewayMerchant/GetWithdrawOrder"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BcApiGatewayMerchant_GetWithdrawOrder_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetWithdrawOrder_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_BcApiGatewayMerchant_GetOrderListByLimitAndOffset_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetOrderListByLimitAndOffset", runtime.WithHTTPPathPattern("/api.BcApiGatewayMerchant/GetOrderListByLimitAndOffset"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BcApiGatewayMerchant_GetOrderListByLimitAndOffset_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetOrderListByLimitAndOffset_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_BcApiGatewayMerchant_GetWallets_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetWallets", runtime.WithHTTPPathPattern("/api/admin/GetWallets/{NetworkIdentifier}/{ProviderIdentifier}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BcApiGatewayMerchant_GetWallets_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetWallets_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_BcApiGatewayMerchant_GetCurrencies_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetCurrencies", runtime.WithHTTPPathPattern("/api/admin/GetCurrencies"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BcApiGatewayMerchant_GetCurrencies_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetCurrencies_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_BcApiGatewayMerchant_GetWalletBalance_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetWalletBalance", runtime.WithHTTPPathPattern("/api/admin/GetBalance/{NetworkIdentifier}/{CurrencyIdentifier.UUID}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BcApiGatewayMerchant_GetWalletBalance_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetWalletBalance_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_BcApiGatewayMerchant_GetOrderInfo_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetOrderInfo", runtime.WithHTTPPathPattern("/api/admin/GetOrder/{NetworkIdentifier}/{ProviderIdentifier}/{OrderIdentifier.UUID}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BcApiGatewayMerchant_GetOrderInfo_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetOrderInfo_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_BcApiGatewayMerchant_GetOrderListByTimeRange_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetOrderListByTimeRange", runtime.WithHTTPPathPattern("/api/admin/GetOrders/{TimeRange.Start}/{TimeRange.End}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BcApiGatewayMerchant_GetOrderListByTimeRange_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetOrderListByTimeRange_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_BcApiGatewayMerchant_GetEventList_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/api.BcApiGatewayMerchant/GetEventList", runtime.WithHTTPPathPattern("/api/admin/GetOrderEvents/{NetworkIdentifier}/{ProviderIdentifier}/{OrderIdentifier.UUID}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BcApiGatewayMerchant_GetEventList_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_BcApiGatewayMerchant_GetEventList_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	return nil
}

var (
	pattern_BcApiGatewayMerchant_CreateWithdrawOrder_0          = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"api.BcApiGatewayMerchant", "CreateWithdrawOrder"}, ""))
	pattern_BcApiGatewayMerchant_AddAccountCurrency_0           = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"api.BcApiGatewayMerchant", "AddAccountCurrency"}, ""))
	pattern_BcApiGatewayMerchant_GetDepositAddress_0            = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"api.BcApiGatewayMerchant", "GetDepositAddress"}, ""))
	pattern_BcApiGatewayMerchant_GetEstimationFee_0             = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"api.BcApiGatewayMerchant", "GetEstimationFee"}, ""))
	pattern_BcApiGatewayMerchant_GetTransaction_0               = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"api.BcApiGatewayMerchant", "GetTransaction"}, ""))
	pattern_BcApiGatewayMerchant_GetWithdrawOrder_0             = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"api.BcApiGatewayMerchant", "GetWithdrawOrder"}, ""))
	pattern_BcApiGatewayMerchant_GetOrderListByLimitAndOffset_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"api.BcApiGatewayMerchant", "GetOrderListByLimitAndOffset"}, ""))
	pattern_BcApiGatewayMerchant_GetWallets_0                   = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3, 1, 0, 4, 1, 5, 4}, []string{"api", "admin", "GetWallets", "NetworkIdentifier", "ProviderIdentifier"}, ""))
	pattern_BcApiGatewayMerchant_GetCurrencies_0                = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"api", "admin", "GetCurrencies"}, ""))
	pattern_BcApiGatewayMerchant_GetWalletBalance_0             = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3, 1, 0, 4, 1, 5, 4}, []string{"api", "admin", "GetBalance", "NetworkIdentifier", "CurrencyIdentifier.UUID"}, ""))
	pattern_BcApiGatewayMerchant_GetOrderInfo_0                 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3, 1, 0, 4, 1, 5, 4, 1, 0, 4, 1, 5, 5}, []string{"api", "admin", "GetOrder", "NetworkIdentifier", "ProviderIdentifier", "OrderIdentifier.UUID"}, ""))
	pattern_BcApiGatewayMerchant_GetOrderListByTimeRange_0      = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3, 1, 0, 4, 1, 5, 4}, []string{"api", "admin", "GetOrders", "TimeRange.Start", "TimeRange.End"}, ""))
	pattern_BcApiGatewayMerchant_GetEventList_0                 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3, 1, 0, 4, 1, 5, 4, 1, 0, 4, 1, 5, 5}, []string{"api", "admin", "GetOrderEvents", "NetworkIdentifier", "ProviderIdentifier", "OrderIdentifier.UUID"}, ""))
)

var (
	forward_BcApiGatewayMerchant_CreateWithdrawOrder_0          = runtime.ForwardResponseMessage
	forward_BcApiGatewayMerchant_AddAccountCurrency_0           = runtime.ForwardResponseMessage
	forward_BcApiGatewayMerchant_GetDepositAddress_0            = runtime.ForwardResponseMessage
	forward_BcApiGatewayMerchant_GetEstimationFee_0             = runtime.ForwardResponseMessage
	forward_BcApiGatewayMerchant_GetTransaction_0               = runtime.ForwardResponseMessage
	forward_BcApiGatewayMerchant_GetWithdrawOrder_0             = runtime.ForwardResponseMessage
	forward_BcApiGatewayMerchant_GetOrderListByLimitAndOffset_0 = runtime.ForwardResponseMessage
	forward_BcApiGatewayMerchant_GetWallets_0                   = runtime.ForwardResponseMessage
	forward_BcApiGatewayMerchant_GetCurrencies_0                = runtime.ForwardResponseMessage
	forward_BcApiGatewayMerchant_GetWalletBalance_0             = runtime.ForwardResponseMessage
	forward_BcApiGatewayMerchant_GetOrderInfo_0                 = runtime.ForwardResponseMessage
	forward_BcApiGatewayMerchant_GetOrderListByTimeRange_0      = runtime.ForwardResponseMessage
	forward_BcApiGatewayMerchant_GetEventList_0                 = runtime.ForwardResponseMessage
)
