// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: api_merchant.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BcApiGatewayMerchant_CreateWithdrawOrder_FullMethodName          = "/api.BcApiGatewayMerchant/CreateWithdrawOrder"
	BcApiGatewayMerchant_AddAccountCurrency_FullMethodName           = "/api.BcApiGatewayMerchant/AddAccountCurrency"
	BcApiGatewayMerchant_GetDepositAddress_FullMethodName            = "/api.BcApiGatewayMerchant/GetDepositAddress"
	BcApiGatewayMerchant_GetEstimationFee_FullMethodName             = "/api.BcApiGatewayMerchant/GetEstimationFee"
	BcApiGatewayMerchant_GetTransaction_FullMethodName               = "/api.BcApiGatewayMerchant/GetTransaction"
	BcApiGatewayMerchant_GetWithdrawOrder_FullMethodName             = "/api.BcApiGatewayMerchant/GetWithdrawOrder"
	BcApiGatewayMerchant_GetOrderListByLimitAndOffset_FullMethodName = "/api.BcApiGatewayMerchant/GetOrderListByLimitAndOffset"
	BcApiGatewayMerchant_GetWallets_FullMethodName                   = "/api.BcApiGatewayMerchant/GetWallets"
	BcApiGatewayMerchant_GetCurrencies_FullMethodName                = "/api.BcApiGatewayMerchant/GetCurrencies"
	BcApiGatewayMerchant_GetWalletBalance_FullMethodName             = "/api.BcApiGatewayMerchant/GetWalletBalance"
	BcApiGatewayMerchant_GetOrderInfo_FullMethodName                 = "/api.BcApiGatewayMerchant/GetOrderInfo"
	BcApiGatewayMerchant_GetOrderListByTimeRange_FullMethodName      = "/api.BcApiGatewayMerchant/GetOrderListByTimeRange"
	BcApiGatewayMerchant_GetEventList_FullMethodName                 = "/api.BcApiGatewayMerchant/GetEventList"
)

// BcApiGatewayMerchantClient is the client API for BcApiGatewayMerchant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Merchant RPC api gateway
type BcApiGatewayMerchantClient interface {
	CreateWithdrawOrder(ctx context.Context, in *CreateWithdrawOrderRequest, opts ...grpc.CallOption) (*CreateWithdrawOrderResponse, error)
	AddAccountCurrency(ctx context.Context, in *AddAccountCurrencyRequest, opts ...grpc.CallOption) (*AddAccountCurrencyResponse, error)
	GetDepositAddress(ctx context.Context, in *GetDepositAddressRequest, opts ...grpc.CallOption) (*GetDepositAddressResponse, error)
	GetEstimationFee(ctx context.Context, in *GetEstimationFeeRequest, opts ...grpc.CallOption) (*GetEstimationFeeResponse, error)
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	GetWithdrawOrder(ctx context.Context, in *GetWithdrawOrderRequest, opts ...grpc.CallOption) (*GetWithdrawOrderResponse, error)
	GetOrderListByLimitAndOffset(ctx context.Context, in *GetOrderListByLimitAndOffsetRequest, opts ...grpc.CallOption) (*GetOrderListByLimitAndOffsetResponse, error)
	GetWallets(ctx context.Context, in *GetWalletsRequest, opts ...grpc.CallOption) (*GetWalletsResponse, error)
	GetCurrencies(ctx context.Context, in *GetCurrenciesRequest, opts ...grpc.CallOption) (*GetCurrenciesResponse, error)
	GetWalletBalance(ctx context.Context, in *GetWalletBalanceRequest, opts ...grpc.CallOption) (*GetWalletBalanceResponse, error)
	GetOrderInfo(ctx context.Context, in *GetOrderInfoRequest, opts ...grpc.CallOption) (*GetOrderInfoResponse, error)
	GetOrderListByTimeRange(ctx context.Context, in *GetOrderListByTimeRangeRequest, opts ...grpc.CallOption) (*GetOrderListByTimeRangeResponse, error)
	GetEventList(ctx context.Context, in *GetEventListRequest, opts ...grpc.CallOption) (*GetEventListResponse, error)
}

type bcApiGatewayMerchantClient struct {
	cc grpc.ClientConnInterface
}

func NewBcApiGatewayMerchantClient(cc grpc.ClientConnInterface) BcApiGatewayMerchantClient {
	return &bcApiGatewayMerchantClient{cc}
}

func (c *bcApiGatewayMerchantClient) CreateWithdrawOrder(ctx context.Context, in *CreateWithdrawOrderRequest, opts ...grpc.CallOption) (*CreateWithdrawOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWithdrawOrderResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayMerchant_CreateWithdrawOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayMerchantClient) AddAccountCurrency(ctx context.Context, in *AddAccountCurrencyRequest, opts ...grpc.CallOption) (*AddAccountCurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAccountCurrencyResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayMerchant_AddAccountCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayMerchantClient) GetDepositAddress(ctx context.Context, in *GetDepositAddressRequest, opts ...grpc.CallOption) (*GetDepositAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepositAddressResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayMerchant_GetDepositAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayMerchantClient) GetEstimationFee(ctx context.Context, in *GetEstimationFeeRequest, opts ...grpc.CallOption) (*GetEstimationFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEstimationFeeResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayMerchant_GetEstimationFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayMerchantClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayMerchant_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayMerchantClient) GetWithdrawOrder(ctx context.Context, in *GetWithdrawOrderRequest, opts ...grpc.CallOption) (*GetWithdrawOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawOrderResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayMerchant_GetWithdrawOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayMerchantClient) GetOrderListByLimitAndOffset(ctx context.Context, in *GetOrderListByLimitAndOffsetRequest, opts ...grpc.CallOption) (*GetOrderListByLimitAndOffsetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderListByLimitAndOffsetResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayMerchant_GetOrderListByLimitAndOffset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayMerchantClient) GetWallets(ctx context.Context, in *GetWalletsRequest, opts ...grpc.CallOption) (*GetWalletsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletsResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayMerchant_GetWallets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayMerchantClient) GetCurrencies(ctx context.Context, in *GetCurrenciesRequest, opts ...grpc.CallOption) (*GetCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrenciesResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayMerchant_GetCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayMerchantClient) GetWalletBalance(ctx context.Context, in *GetWalletBalanceRequest, opts ...grpc.CallOption) (*GetWalletBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletBalanceResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayMerchant_GetWalletBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayMerchantClient) GetOrderInfo(ctx context.Context, in *GetOrderInfoRequest, opts ...grpc.CallOption) (*GetOrderInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderInfoResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayMerchant_GetOrderInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayMerchantClient) GetOrderListByTimeRange(ctx context.Context, in *GetOrderListByTimeRangeRequest, opts ...grpc.CallOption) (*GetOrderListByTimeRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderListByTimeRangeResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayMerchant_GetOrderListByTimeRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcApiGatewayMerchantClient) GetEventList(ctx context.Context, in *GetEventListRequest, opts ...grpc.CallOption) (*GetEventListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventListResponse)
	err := c.cc.Invoke(ctx, BcApiGatewayMerchant_GetEventList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BcApiGatewayMerchantServer is the server API for BcApiGatewayMerchant service.
// All implementations must embed UnimplementedBcApiGatewayMerchantServer
// for forward compatibility.
//
// Merchant RPC api gateway
type BcApiGatewayMerchantServer interface {
	CreateWithdrawOrder(context.Context, *CreateWithdrawOrderRequest) (*CreateWithdrawOrderResponse, error)
	AddAccountCurrency(context.Context, *AddAccountCurrencyRequest) (*AddAccountCurrencyResponse, error)
	GetDepositAddress(context.Context, *GetDepositAddressRequest) (*GetDepositAddressResponse, error)
	GetEstimationFee(context.Context, *GetEstimationFeeRequest) (*GetEstimationFeeResponse, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	GetWithdrawOrder(context.Context, *GetWithdrawOrderRequest) (*GetWithdrawOrderResponse, error)
	GetOrderListByLimitAndOffset(context.Context, *GetOrderListByLimitAndOffsetRequest) (*GetOrderListByLimitAndOffsetResponse, error)
	GetWallets(context.Context, *GetWalletsRequest) (*GetWalletsResponse, error)
	GetCurrencies(context.Context, *GetCurrenciesRequest) (*GetCurrenciesResponse, error)
	GetWalletBalance(context.Context, *GetWalletBalanceRequest) (*GetWalletBalanceResponse, error)
	GetOrderInfo(context.Context, *GetOrderInfoRequest) (*GetOrderInfoResponse, error)
	GetOrderListByTimeRange(context.Context, *GetOrderListByTimeRangeRequest) (*GetOrderListByTimeRangeResponse, error)
	GetEventList(context.Context, *GetEventListRequest) (*GetEventListResponse, error)
	mustEmbedUnimplementedBcApiGatewayMerchantServer()
}

// UnimplementedBcApiGatewayMerchantServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBcApiGatewayMerchantServer struct{}

func (UnimplementedBcApiGatewayMerchantServer) CreateWithdrawOrder(context.Context, *CreateWithdrawOrderRequest) (*CreateWithdrawOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWithdrawOrder not implemented")
}
func (UnimplementedBcApiGatewayMerchantServer) AddAccountCurrency(context.Context, *AddAccountCurrencyRequest) (*AddAccountCurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAccountCurrency not implemented")
}
func (UnimplementedBcApiGatewayMerchantServer) GetDepositAddress(context.Context, *GetDepositAddressRequest) (*GetDepositAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepositAddress not implemented")
}
func (UnimplementedBcApiGatewayMerchantServer) GetEstimationFee(context.Context, *GetEstimationFeeRequest) (*GetEstimationFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEstimationFee not implemented")
}
func (UnimplementedBcApiGatewayMerchantServer) GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedBcApiGatewayMerchantServer) GetWithdrawOrder(context.Context, *GetWithdrawOrderRequest) (*GetWithdrawOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWithdrawOrder not implemented")
}
func (UnimplementedBcApiGatewayMerchantServer) GetOrderListByLimitAndOffset(context.Context, *GetOrderListByLimitAndOffsetRequest) (*GetOrderListByLimitAndOffsetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderListByLimitAndOffset not implemented")
}
func (UnimplementedBcApiGatewayMerchantServer) GetWallets(context.Context, *GetWalletsRequest) (*GetWalletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWallets not implemented")
}
func (UnimplementedBcApiGatewayMerchantServer) GetCurrencies(context.Context, *GetCurrenciesRequest) (*GetCurrenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrencies not implemented")
}
func (UnimplementedBcApiGatewayMerchantServer) GetWalletBalance(context.Context, *GetWalletBalanceRequest) (*GetWalletBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletBalance not implemented")
}
func (UnimplementedBcApiGatewayMerchantServer) GetOrderInfo(context.Context, *GetOrderInfoRequest) (*GetOrderInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderInfo not implemented")
}
func (UnimplementedBcApiGatewayMerchantServer) GetOrderListByTimeRange(context.Context, *GetOrderListByTimeRangeRequest) (*GetOrderListByTimeRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderListByTimeRange not implemented")
}
func (UnimplementedBcApiGatewayMerchantServer) GetEventList(context.Context, *GetEventListRequest) (*GetEventListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventList not implemented")
}
func (UnimplementedBcApiGatewayMerchantServer) mustEmbedUnimplementedBcApiGatewayMerchantServer() {}
func (UnimplementedBcApiGatewayMerchantServer) testEmbeddedByValue()                              {}

// UnsafeBcApiGatewayMerchantServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BcApiGatewayMerchantServer will
// result in compilation errors.
type UnsafeBcApiGatewayMerchantServer interface {
	mustEmbedUnimplementedBcApiGatewayMerchantServer()
}

func RegisterBcApiGatewayMerchantServer(s grpc.ServiceRegistrar, srv BcApiGatewayMerchantServer) {
	// If the following call pancis, it indicates UnimplementedBcApiGatewayMerchantServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BcApiGatewayMerchant_ServiceDesc, srv)
}

func _BcApiGatewayMerchant_CreateWithdrawOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWithdrawOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayMerchantServer).CreateWithdrawOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayMerchant_CreateWithdrawOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayMerchantServer).CreateWithdrawOrder(ctx, req.(*CreateWithdrawOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayMerchant_AddAccountCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccountCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayMerchantServer).AddAccountCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayMerchant_AddAccountCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayMerchantServer).AddAccountCurrency(ctx, req.(*AddAccountCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayMerchant_GetDepositAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepositAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayMerchantServer).GetDepositAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayMerchant_GetDepositAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayMerchantServer).GetDepositAddress(ctx, req.(*GetDepositAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayMerchant_GetEstimationFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEstimationFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayMerchantServer).GetEstimationFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayMerchant_GetEstimationFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayMerchantServer).GetEstimationFee(ctx, req.(*GetEstimationFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayMerchant_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayMerchantServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayMerchant_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayMerchantServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayMerchant_GetWithdrawOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayMerchantServer).GetWithdrawOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayMerchant_GetWithdrawOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayMerchantServer).GetWithdrawOrder(ctx, req.(*GetWithdrawOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayMerchant_GetOrderListByLimitAndOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderListByLimitAndOffsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayMerchantServer).GetOrderListByLimitAndOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayMerchant_GetOrderListByLimitAndOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayMerchantServer).GetOrderListByLimitAndOffset(ctx, req.(*GetOrderListByLimitAndOffsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayMerchant_GetWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayMerchantServer).GetWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayMerchant_GetWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayMerchantServer).GetWallets(ctx, req.(*GetWalletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayMerchant_GetCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayMerchantServer).GetCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayMerchant_GetCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayMerchantServer).GetCurrencies(ctx, req.(*GetCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayMerchant_GetWalletBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayMerchantServer).GetWalletBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayMerchant_GetWalletBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayMerchantServer).GetWalletBalance(ctx, req.(*GetWalletBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayMerchant_GetOrderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayMerchantServer).GetOrderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayMerchant_GetOrderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayMerchantServer).GetOrderInfo(ctx, req.(*GetOrderInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayMerchant_GetOrderListByTimeRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderListByTimeRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayMerchantServer).GetOrderListByTimeRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayMerchant_GetOrderListByTimeRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayMerchantServer).GetOrderListByTimeRange(ctx, req.(*GetOrderListByTimeRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcApiGatewayMerchant_GetEventList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcApiGatewayMerchantServer).GetEventList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcApiGatewayMerchant_GetEventList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcApiGatewayMerchantServer).GetEventList(ctx, req.(*GetEventListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BcApiGatewayMerchant_ServiceDesc is the grpc.ServiceDesc for BcApiGatewayMerchant service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BcApiGatewayMerchant_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.BcApiGatewayMerchant",
	HandlerType: (*BcApiGatewayMerchantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWithdrawOrder",
			Handler:    _BcApiGatewayMerchant_CreateWithdrawOrder_Handler,
		},
		{
			MethodName: "AddAccountCurrency",
			Handler:    _BcApiGatewayMerchant_AddAccountCurrency_Handler,
		},
		{
			MethodName: "GetDepositAddress",
			Handler:    _BcApiGatewayMerchant_GetDepositAddress_Handler,
		},
		{
			MethodName: "GetEstimationFee",
			Handler:    _BcApiGatewayMerchant_GetEstimationFee_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _BcApiGatewayMerchant_GetTransaction_Handler,
		},
		{
			MethodName: "GetWithdrawOrder",
			Handler:    _BcApiGatewayMerchant_GetWithdrawOrder_Handler,
		},
		{
			MethodName: "GetOrderListByLimitAndOffset",
			Handler:    _BcApiGatewayMerchant_GetOrderListByLimitAndOffset_Handler,
		},
		{
			MethodName: "GetWallets",
			Handler:    _BcApiGatewayMerchant_GetWallets_Handler,
		},
		{
			MethodName: "GetCurrencies",
			Handler:    _BcApiGatewayMerchant_GetCurrencies_Handler,
		},
		{
			MethodName: "GetWalletBalance",
			Handler:    _BcApiGatewayMerchant_GetWalletBalance_Handler,
		},
		{
			MethodName: "GetOrderInfo",
			Handler:    _BcApiGatewayMerchant_GetOrderInfo_Handler,
		},
		{
			MethodName: "GetOrderListByTimeRange",
			Handler:    _BcApiGatewayMerchant_GetOrderListByTimeRange_Handler,
		},
		{
			MethodName: "GetEventList",
			Handler:    _BcApiGatewayMerchant_GetEventList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_merchant.proto",
}
